### ISSUE TITLE
`fallocate` doesn't work on F2FS or XFS

### ISSUE THREAD

**Issue by riaqn** [Tookmund/Swapspace#10]
On XFS or F2FS `fallocate` creates illegal swapfile, `swapon` such file returns `invalid arguments`.

The correct method is to fill the file with zero, which is slow but works.

**Comment by Tookmund** [comment]
swapspace does have this method as a fallback when posix_fallocate is unavailable.
As of d329058 , you can use the ````--enable-no-posix-fallocate```` to fallback on the previous "fill file with zeros" method
