### ISSUE TITLE
Support loopback mounting (required for btrfs)

### ISSUE THREAD

**Issue by HaleTom** [Tookmund/Swapspace#11]
`btrfs` can only use swapfiles when loopback mounted.

Would you consider supporting this?

**Comment by wmertens** [comment]
Would this help? https://github.com/Nefelim4ag/systemd-swap

**Comment by HaleTom** [comment]
@wmertens Very nice!

Now if only I could suspend/resume...

**Comment by Tookmund** [comment]
Suspend/resume requires the computer to have enough swapspace to hold its entire memory. Swapspace (the program) does not guarantee this and thus can't be used if you want suspend/resume to work.

btrfs appears to intentionally not support swapfiles, and so I would recommend just using a swap partition, especially if you want suspend to work.
I might accept a patch for loopback mounting as a workaround, but really for most modern systems I'd recommend a static swapfile or partition instead.

**Comment by wmertens** [comment]
It is worth noting that macOS seems to manage swapfiles and suspending just
fine…

**Comment by chungy** [comment]
Likewise, on file systems supporting swap files on Linux (eg, XFS and ext4), suspend-to-disk works fine there too.

It is the CoW file systems (such as ZFS and btrfs) that don't support swap files, though there are workarounds such as using a loopback device, it still won't give you the suspend functionality. Just use a partition instead if you require the feature as well as one of these file systems.

**Comment by wmertens** [comment]
Oh right, of course - I thought the problem was that swapspace can't
provide a minimal swap file size.

**Comment by Tookmund** [comment]
As swapfiles aren't really supported on CoW filesystems, I'm closing this issue.
If anyone knows of a better workaround, feel free to reopen it.

**Comment by ysolis** [comment]
btrfs support now swapfiles with Linux kernel 5.0+ ... you need to create the swap file, disable compression and CoW for this file.

Can be possible to add this flags to the swap file creation with a config parameter ?

**Comment by Tookmund** [comment]
Certainly possible, pull requests welcome!

For reference
https://wiki.archlinux.org/index.php/Swap#Swap_file_creation
says these commands are required to setup a swapfile correctly for btrfs

```
# truncate -s 0 /swapfile
# chattr +C /swapfile
# btrfs property set /swapfile compression none
```
(and then fallocate swapfile)
