### ISSUE TITLE
Swapspace doesn't remove swapfile

### ISSUE THREAD

**Issue by oktorok** [Tookmund/Swapspace#15]
Hi, i have just installed swapspace in an ubuntu 18.04 server, the reallocation of swapfiles is correct but in the moment i stop my programs the swapfiles arent removed, i tried to execute swapspace -e only for test and give me an error about:
 "Could not enamble swapfile '2': Device or resource busy"
But when i check with 
"swapon --show"
the swapfile '2' is completly empty. Did i miss some configuration or somewthing?

**Comment by Tookmund** [comment]
Swapspace is designed not to deallocate the swapfile immediately in case more memory is needed soon. Swapfile allocation is a relatively expensive operation. 
Thus we wait for a bit (600 runs of its main loop) before deallocating a swapfile. 

For more details see:
https://github.com/Tookmund/Swapspace/blob/master/doc/technicaldetails

Or the place where it’s implemented:
https://github.com/Tookmund/Swapspace/blob/master/src/state.c

You can run the program with the verbose flag to see what it’s doing at any given time.

**Comment by oktorok** [comment]
It has been almost a day and the swapfiles still there, and i can't make swapspace -e or service swapspace restart for remove the swapfiles. I could make service swapspace stop and swapoff -all but i would prefer to be authomatic, any idea?

**Comment by Tookmund** [comment]
That definitely shouldn’t be happening 
What’s the output of swapon --show look like currently?

Can you try stopping the service, running swapoff and removing the file. 
Then restart with --verbose and recreate the situation.

That way it should log what’s happening and should give some insight into why it’s not working correctly. 

Jacob

**Comment by oktorok** [comment]
I have done this:

1. `sudo service stop swapspace`
2. `sudo swapspace -v`
[in another terminal]
3. *program that use a lot of RAM for check swapspace*
4. *wait for swapspace allocate something and stop program*

this is the output from swapspace:

steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
Notice: Allocating swapfile '1'
Setting up swapspace version 1, size = 8 GiB (8589930496 bytes)
no label, UUID=65665f5c-d765-4140-8471-269a4443baff
steady -> hungry
hungry -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
steady -> overfed
overfed -> steady
*and goes on like that*

A thing that i have thought is: i have installed swapspace from apt install, is it possible that the apt version is outdated or something and the correct one is compiling from source?

**Comment by Tookmund** [comment]
You're a few versions behind, but this appears to be an issue with the state machine, which has not seen any changes since the version you're on. 

However, if you can update to current master, I've just pushed a change that should increase verbosity a bit so we can see what's going on here.

If you could update and log swapspace output to a file after repeating the steps you took above that would be much appreciated.

**Comment by oktorok** [comment]
I have purged swapspace and reinstalled it from source

Now when i execute `swapspace` it creates automatically a swapfile (is not a bad thing is only that before it didn't do it) and i have notice a faster performance reallocating new swapfiles. Despite that still not deallocating the swapfiles but now if i execute swapspace -e it, deallocates the swapfiles.

Anyway the output of the process is in this file

[log.txt](https://github.com/Tookmund/Swapspace/files/3143774/log.txt)

**Comment by Tookmund** [comment]
Sorry been caught up in other projects. 
That’s very odd. 
Going to setup a VM with similar specs to see if I can reproduce the issue. 

Jacob

**Comment by oktorok** [comment]
Uff sorry, I forgot totally too 😅

It was working good since I did the purge and compile from source, im not sure how much time does it take, but at the end the swap memory is deallocated correctly.

In the test didn't work maybe because I needed reboot first, maybe because I didn't wait enoguht time I'm not completely sure but know is working

Thank you for everything and sorry, for not say anything before.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Tookmund** [comment]
Don’t worry about it! Glad it’s now working properly
