### ISSUE TITLE
Manjaro ARH based AUR Install Query

### ISSUE THREAD

**Issue by PeterKW** [Tookmund/Swapspace#28]
I have downloaded Swapspace from the AUR successfully: https://aur.archlinux.org/packages/swapspace

I'm not quite sure what to do next to get it going. The swapspace folder exists in /var/lib/ as attached but I don't see swapspace running or making a difference to my swap file even after a restart so I'm assuming I have missed something. man -l doc/swapspace.8 outputs No such file or directory with No manual entry for swapspace

Is there anything else to try to get it working from the AUR?
![image](https://user-images.githubusercontent.com/13779157/106818599-6b72fb80-6670-11eb-9cb3-df80433bd158.png)

**Comment by PeterKW** [comment]
Ah okay, do I just need to uncomment some of the lines in /etc/swapspace.conf ?

**Comment by Tookmund** [comment]
Assuming everything is installed correctly by the AUR package it should just work, no config file editing required.

The AUR package is maintained by @chungy
Pinging in case he has specific advice. 

Have you tried checking the output of:

systemd status swapspace

If it says disabled, try:

systemd enable swapspace

Jacob

**Comment by PeterKW** [comment]
![image](https://user-images.githubusercontent.com/13779157/106962223-b35c5600-6736-11eb-9873-6f02d6c8a258.png)
It says -bash: systemd: command not found which I don't really understand. It doesn't look like systemd is disabled in my settings gui?
Anything else that I could try?
Thank you very much

**Comment by Tookmund** [comment]
Whoops sorry wrong command. 

systemctl status swapspace

Most likely it's running and just not doing anything.

**Comment by PeterKW** [comment]
Thank you very much. I pressume it will need to activate the next time I startup my computer and it'll make the swapfiles required without me doing anything more?

$ systemctl status swapspace
● swapspace.service - dynamic swap manager
Loaded: loaded (/usr/lib/systemd/system/swapspace.service; disabled; vendor preset: disabled)
Active: inactive (dead)
Docs: man:swapspace(8)

systemctl enable swapspace
Created symlink /etc/systemd/system/multi-user.target.wants/swapspace.service → /usr/lib/systemd/system/swapspace.service.

swapon
NAME      TYPE SIZE USED PRIO
/swapfile file 512M 512M   -2

**Comment by Tookmund** [comment]
Now that you've enabled it, it should start itself on next reboot. To start it immediately, use: systemctl start swapspace

After that it should just work, yes. Please reopen this issue if it doesn't.
