### ISSUE TITLE
Automake failed when running "autoreconf"

### ISSUE THREAD

**Issue by eibay** [Tookmund/Swapspace#29]
Probably just an issue on my mac when I ran "autoreconf",  but just in case other people encounter the same error, good to know how to fix this.. 
```
(base) ➜  Swapspace git:(master) autoreconf                      
configure.ac:30: error: required file './config.guess' not found
configure.ac:30:   'automake --add-missing' can install 'config.guess'
configure.ac:30: error: required file './config.sub' not found
configure.ac:30:   'automake --add-missing' can install 'config.sub'
autoreconf: error: automake failed with exit status: 1
```

**Comment by Tookmund** [comment]
I believe `autoreconf -i` will automatically fix this. If that works for you I'll update the README to mention it. 

Not that this program will actually configure correctly on a Mac, I should probably make sure configure explicitly checks for that.

**Comment by eibay** [comment]
Thanks, I was able to proceed without error by running `autoreconf -i`.  
Two files were generated after that: 
config.guess and config.sub
