### ISSUE TITLE
Deb package update 

### ISSUE THREAD

**Issue by modem7** [Tookmund/Swapspace#39]
Heya @Tookmund,

Will the 1.18 package be rolled out to the deb repos at all?

Unsure how complicated it is, so speaking from a place of ignorance here! 

Just saw the "action needed" bit of https://tracker.debian.org/pkg/swapspace so was naturally curious! 

Thanks!

**Comment by Tookmund** [comment]
Thanks for the reminder, I missed this when going through my typical release process.
I've got a new version up on mentors now, https://mentors.debian.net/package/swapspace/
Assuming no major issues it should make it into debian in the next few weeks.
