### ISSUE TITLE
swapspace for hibernation

### ISSUE THREAD

**Issue by addadi** [Tookmund/Swapspace#8]
Hello,
Is it possible to use swapspace for hibernation. If so, how? typically I need to use resume kernel flagging in grub to mark the swap file (or partition).
thanks

**Comment by Tookmund** [comment]
No sorry I can't see how that would work. You can't know if a swapfile managed by Swapspace is available and there might not even be enough swapspace to fully hibernate your system if you aren't doing much beforehand. 

I'm closing this as it doesn't seem feasible. If you can think of some way for this to work, feel free to reopen it.

**Comment by addadi** [comment]
thanks
