### ISSUE TITLE
Old upstream released a 1.11 version, too

### ISSUE THREAD

**Issue by eMPee584** [Tookmund/Swapspace#9]
```
+swapspace (1.11) stable; urgency=high
+  * Use posix_fallocate() to save writing to swap file.
+
+ -- Jeroen T. Vermeulen <jtv@...>  Wed, 03 Jun 2015 09:20:00 +0700

```

**Comment by Tookmund** [comment]
Changes adopted in 385085c712437a784307c71dc319d036e1440455

**Comment by eMPee584** [comment]
That doesn't quite solve the confusion of what the relevant upstream of swapspace is..
Could you rebase your tree on origin?

**Comment by Tookmund** [comment]
I’m not sure why there’s confusion. The form happened in 2014 and then upstream made a release in 2015, whose changes I merged back into the fork. I can’t see what advantage there would be to rewriting history. 
It’s quite a few git commits and I’d rather not go messing around with rebase just to make the fork seem “cleaner”

Jacob
